u1 = User.create!(username: "Zlatan", first_name: "Zlatan", last_name:"Ibrahimovich", email: "a@a.com", password: "password", password_confirmation: "password")
u2 = User.create!(username: "Messi", first_name: "Lionel", last_name:"Messi", email: "b@b.com", password: "password", password_confirmation: "password")
u3 = User.create!(username: "Cristiano", first_name: "Cristiano", last_name:"Ronaldo", email: "c@c.com", password: "password", password_confirmation: "password")
u4 = User.create!(username: "Sadio", first_name: "Sadio", last_name:"Mane", email: "d@d.com", password: "password", password_confirmation: "password")
u5 = User.create!(username: "Petr", first_name: "Petr", last_name: "Cech", email: "w@w.com", password: "password", password_confirmation: "password")

t1 = Team.create!(name: "TeamOne", image: "https://pbs.twimg.com/profile_images/378800000797610573/af1e7e90714a54249d00c6eae8b85f22_400x400.jpeg", description: "we the best", creator_id: 1)
t1 = Team.create!(name: "TeamTwo", image: "https://pbs.twimg.com/profile_images/848471660860538880/pevXVsIp_400x400.jpg", description: "Hi. Looking for last player for our 5 a side team. You have to play defense.", creator_id: 1)
t1 = Team.create!(name: "TeamThree", image: "http://images.nike.com/is/image/DotCom/PDP_THUMB_RETINA/833390_371/alpha-field-general-elite-camo-mens-football-cleat.jpg", description: "Looking for players to play 5 a side. 19:00-21:00 on sundays", creator_id: 2)
t1 = Team.create!(name: "TeamFour", image: "https://pbs.twimg.com/profile_images/589104941047934976/Tzmj2HsY.jpg", description: "We are serious", creator_id: 3)
t1 = Team.create!(name: "TeamFive", image: "http://images.nike.com/is/image/DotCom/PHN_PS/SC2987_100_A/strike-premier-league-football.png?fmt=png-alpha", description: "Team number five.", creator_id: 3)
