u1 = User.create!(username: "Zlatan", first_name: "Zlatan", last_name:"Ibrahimovich", email: "a@a.com", password: "password", password_confirmation: "password")
u2 = User.create!(username: "Messi", first_name: "Lionel", last_name:"Messi", email: "b@b.com", password: "password", password_confirmation: "password")
u3 = User.create!(username: "Ronaldo", first_name: "Cristiano", last_name:"Ronaldo", email: "c@c.com", password: "password", password_confirmation: "password")
u4 = User.create!(username: "Mane", first_name: "Sadio", last_name:"Mane", email: "d@d.com", password: "password", password_confirmation: "password")
u5 = User.create!(username: "Totti", first_name: "Totti", last_name: "Totti", email: "w@w.com", password: "password", password_confirmation: "password")

t1 = Team.create!(name: "Froglegs", image: "http://assets.stickpng.com/thumbs/584c94451f591a0c7cef3d41.png", description: "we the best", creator_id: 1)
t1 = Team.create!(name: "TeamTwo", image: "http://images.nike.com/is/image/DotCom/PHN_PS/SC2987_100_A/strike-premier-league-football.png?fmt=png-alpha", description: "Hi. Looking for last player for our 5 a side team. You have to play defense.", creator_id: 1)
t1 = Team.create!(name: "TeamThree", image: "http://images3.nike.com/is/image/DotCom/PHN_PS/831974_301_C_PREM/mercurialx-finale-ii-indoor-court-football-shoe.png?fmt=png-alpha", description: "Looking for players to play 5 a side. 19:00-21:00 on sundays", creator_id: 2)
t1 = Team.create!(name: "TeamFour", image: "https://kansascity-mp7static.mlsdigital.net/elfinderimages/Dribbling%20Icon.png", description: "We are serious", creator_id: 5)
t1 = Team.create!(name: "Rails Madrid", image: "https://vignette4.wikia.nocookie.net/logopedia/images/a/a6/Real-Madrid.png/revision/latest?cb=20160711131706", description: "Team number five.", creator_id: 3)
